permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Jianna.Design"
  description:
    Ottawa-based Graphic Designer & Illustrator, Creative Thinker, Art Enthusiast & Lover Of All Things Shiny!
  font-url: "https://fonts.googleapis.com/css?family=Barlow:100,200,300,400,400i,500,600,700,800,900"
  colors:
    patterns:
      brand.logos: "--color-neutral"
  rationales:
    typefaces.primary: Barlow was selected to to its clean and simple appearance in contrast to the many illustrative works presetned in the portfolio. It also complements the minimalistic grid and simple layout present within the site.
    colors.primary: The primary colour is a dark, ashy grey. It was selected for mainly body copy and presents high readability on white or lighter coloured backgrounds. This colour is neutral and helps ground the colour works it is surrounded by. Primary light is used an transparent overlay when the user hovers over particular works.
    colors.secondary: This canary yellow was selected due to its bold and bright quality. This helps differentiate this site from others and brings a eye-catching element to the to pull users' attention. This is used for header content and the footer background.
    colors.neutral: This neutral beige is used in the top banner on the main page. This colours helps integrate the illustrated icon within the site and allows the site to be responsive within different devices.
