permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Jianna.Design"
  description:
    Ottawa-based Graphic Designer & Illustrator, Creative Thinker, Art Enthusiast & Lover Of All Things Shiny!
  font_url: "https://fonts.googleapis.com/css?family=Barlow:300,400,400i,500,600,700,800,900|Damion&display=swap"
  colors:
    patterns:
      brand.logos: "--color-neutral"
  rationales:
    typefaces.primary: Barlow was selected due to its clean and simple appearance in contrast to the many illustrative works presented in the portfolio. It also complements the minimalistic grid and simple layout present within the site.
    typefaces.secondary: Damion was selected due to its roundness and friendly quality. It fits within the theme for creating a simple site and adds a welcoming, expressive and elegant voice to the homepage.
    colors.primary: The primary colour is a dark, ashy grey. It was selected for mainly body copy and presents high readability on white or lighter coloured backgrounds. This colour is neutral and helps ground the colour works it is surrounded by. Primary light is used an transparent overlay when the user hovers over particular works.
    colors.secondary: This cool blue was selected due to its calming and soft quality. It helps complement the artwork without distracting from it and fits within the theme of simplicity and clean design. This is used a pop of colour in elements such as section headers and the footer background to add visual interest to the site.
    colors.neutral: This neutral beige is used in the top banner on the main page. This colours helps integrate the illustrated icon within the site and allows the site to be responsive within different devices.
