title: "Buttons"
description:
  Buttons are used in situations where a dramatic, obvious action is required. For this site, buttons are used in the main navigation. When hovered buttons adopt the secondary color and a bold weight.

patterns:
  basic:
    title: "Basic"
    description:
      Default to using the basic button it should always be used in front of a light backgrounds.
    width: "12em"
    fields:
    - name: text
      type: string
      example: "works"
  big:
    title: "Big"
    description:
      Used on 404 error page of website.
    width: "12em"
    fields:
    - name: text
      type: string
      example: "Enter site"
