title: "Cards"
description:
  Cards are used as a content container. Used for wide variety of content such as images, headers, and text. Cards are a clean way of displaying information within a simplified grid.

patterns:
  basic:
    title: "description"
    description:
      Used for writing description about the designer and works page. Primary coloured text on partned with a Secondary coloured header, this section is used expand on the details and rationale of a project and provide more detail of the designer's bio.
    width: "12em"
    fields:
    - name: heading
      type: string
      example: "Project Details"
    - name: text
      type: string
      example: "A main objective of this design was to create new packaging that is more sustainable and reduces consumer waste. Within this goal the packaging must maintain its functionality and preserve the overall freshness and quality of the product while also appeal to its target audience who values health and nutrition. This demonstrates ability to thoroughly research the brand and understand the consumers needs and frustrations by applying an innovative solution to their current packaging."
